# Generated by Django 4.2.3 on 2025-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.CharField(default='Novice', max_length=10),
        ),
    ]
